import type {
  AnswerState,
  BouquetCardData,
  BouquetReaction,
  FlowerFamilyId,
  GestureLevelId,
  GiftFormatId,
  GreeneryLevelId,
  LocalizedText,
  Locale,
  OccasionId,
  PaletteId,
  PlantStyleId,
  Question,
  RoseStyleId,
  ShapeId,
  ScentLevelId,
  TulipStyleId,
  VibeId,
  VisualOption,
  WrappingStyleId,
} from './types'
import { textOf } from './content'

const l = (ru: string, en: string): LocalizedText => ({ ru, en })

export const emptyAnswers = (): AnswerState => ({
  palette: [],
  likedFlowers: [],
  avoidFlowers: [],
  bouquetReactions: {},
})

const unsplashPhoto = (path: string) =>
  `https://images.unsplash.com/${path}?auto=format&fit=crop&w=960&q=75`

const photo = {
  peony: unsplashPhoto('photo-1656056970279-0cdd04b60434'),
  tulip: unsplashPhoto('photo-1615385639736-362b69696227'),
  creamRose: unsplashPhoto('photo-1559779080-6970e0186790'),
  ranunculus: unsplashPhoto('photo-1684473339098-dfccf406c68e'),
  sunnyField: unsplashPhoto('photo-1628363462308-68313cc1470b'),
  hydrangea: unsplashPhoto('photo-1660549071168-e71c087ef09e'),
  redRose: unsplashPhoto('photo-1608027790251-5e0c80d043d9'),
  lily: unsplashPhoto('photo-1712258090342-f31b387221a3'),
  marketMix: unsplashPhoto('photo-1596047510164-c33ea1025eae'),
  pottedBloom: unsplashPhoto('photo-1466692476868-aef1dfb1e735'),
  pottedGreen: unsplashPhoto('photo-1485955900006-10f4d324d411'),
  petitePlant: unsplashPhoto('photo-1501004318641-b39e6451bec6'),
} as const

export const giftFormatOptions: VisualOption<GiftFormatId>[] = [
  {
    id: 'cut',
    label: l('Срезанные букеты', 'Cut bouquets'),
    hint: l('Хочется именно букет, а не растение для ухода.', 'A bouquet feels better than a plant to care for.'),
    emoji: '💐',
    celebration: l('Ок, держимся именно букетного сценария.', 'Great, this should stay in bouquet territory.'),
    photoUrl: photo.peony,
  },
  {
    id: 'potted',
    label: l('Растения в горшке', 'Potted plants'),
    hint: l('Нравится, когда подарок живет дольше одного вечера.', 'A longer-living plant feels more special than a cut bouquet.'),
    emoji: '🪴',
    celebration: l('Отмечаю любовь к живым растениям.', 'Nice, potted plants are clearly welcome.'),
    photoUrl: photo.pottedGreen,
  },
  {
    id: 'both',
    label: l('Оба формата ок', 'Both are good'),
    hint: l('Все зависит от повода и как именно это выглядит.', 'It depends on the occasion and how it is styled.'),
    emoji: '✨',
    celebration: l('Супер, значит можно советовать и букеты, и растения.', 'Perfect, both bouquets and plants can stay in play.'),
    photoUrl: photo.pottedBloom,
  },
]

export const vibeOptions: VisualOption<VibeId>[] = [
  {
    id: 'soft',
    label: l('Нежно и воздушно', 'Soft and airy'),
    hint: l('Мягкие оттенки, романтика, ничего резкого.', 'Powdery tones, romance, and nothing too sharp.'),
    emoji: '☁️',
    celebration: l('Поймала очень мягкий вайб.', 'Very soft bouquet energy, noted.'),
    photoUrl: photo.peony,
    swatch: ['#f8d8df', '#fff5ef', '#f6e0cb'],
  },
  {
    id: 'bright',
    label: l('Живо и солнечно', 'Bright and lively'),
    hint: l('Чтобы букет добавлял энергии и настроения.', 'A bouquet that instantly adds energy and good mood.'),
    emoji: '🍊',
    celebration: l('Любишь, когда цветы не молчат.', 'So she likes flowers that do not whisper.'),
    photoUrl: photo.sunnyField,
    swatch: ['#ffbf69', '#ffd166', '#ef476f'],
  },
  {
    id: 'elegant',
    label: l('Собранно и элегантно', 'Clean and elegant'),
    hint: l('Чисто, красиво, благородно и без хаоса.', 'Polished, refined, and never visually messy.'),
    emoji: '🎀',
    celebration: l('Вкус на аккуратную красоту принят.', 'Elegant taste locked in.'),
    photoUrl: photo.creamRose,
    swatch: ['#fff8ef', '#d8d2ca', '#dbcaf2'],
  },
  {
    id: 'dramatic',
    label: l('Вау, с характером', 'Bold, with presence'),
    hint: l('Можно смелее, заметнее и чуть театральнее.', 'A little stronger, bolder, and more dramatic is allowed.'),
    emoji: '🔥',
    celebration: l('Любишь, когда букет умеет произвести впечатление.', 'Okay, she likes a bouquet that can make an entrance.'),
    photoUrl: photo.redRose,
    swatch: ['#5f0f40', '#9a031e', '#f4a261'],
  },
]

export const paletteOptions: VisualOption<PaletteId>[] = [
  {
    id: 'blush',
    label: l('Пудрово-розовый', 'Blush pink'),
    hint: l('Нежный, романтичный и спокойный.', 'Soft, romantic, and calm.'),
    emoji: '🩰',
    celebration: l('Пастель пошла в сердечко.', 'Pastel tones made the cut.'),
    photoUrl: photo.peony,
    swatch: ['#f8d8df', '#f9e6eb', '#f6c8d4'],
  },
  {
    id: 'cream',
    label: l('Кремово-молочный', 'Creamy white'),
    hint: l('Чисто, спокойно и дорого выглядит.', 'Clean, calm, and expensive-looking.'),
    emoji: '🥛',
    celebration: l('Светлая палитра всегда выручает.', 'Light palettes are always safe.'),
    photoUrl: photo.creamRose,
    swatch: ['#fff8ef', '#f5efe2', '#ece5d8'],
  },
  {
    id: 'peach',
    label: l('Персиковый', 'Peach'),
    hint: l('Тепло, мягко и нежно без приторности.', 'Warm and soft without becoming sugary.'),
    emoji: '🍑',
    celebration: l('Теплый оттенок выбран.', 'A warm tone is officially in.'),
    photoUrl: photo.sunnyField,
    swatch: ['#ffc6a8', '#ffd9bf', '#ffb997'],
  },
  {
    id: 'berry',
    label: l('Ягодный', 'Berry'),
    hint: l('Глубже, насыщеннее, но еще романтично.', 'Deeper, richer, still romantic.'),
    emoji: '🍓',
    celebration: l('Есть запрос на насыщенный цвет.', 'There is definitely room for richer color.'),
    photoUrl: photo.redRose,
    swatch: ['#8f2d56', '#b93168', '#d95980'],
  },
  {
    id: 'yellow',
    label: l('Солнечный желтый', 'Sunny yellow'),
    hint: l('Весело, тепло и очень живо.', 'Happy, warm, and very alive.'),
    emoji: '🌼',
    celebration: l('Солнечный цвет добавлен.', 'Sunshine is now part of the palette.'),
    photoUrl: photo.sunnyField,
    swatch: ['#ffd166', '#ffe28a', '#f7b801'],
  },
  {
    id: 'red',
    label: l('Красный акцент', 'Red accent'),
    hint: l('Страстно, заметно, не для каждого повода.', 'Passionate and strong, but not for every moment.'),
    emoji: '❤️',
    celebration: l('В палитре разрешена страсть.', 'Bold romantic color is allowed.'),
    photoUrl: photo.redRose,
    swatch: ['#c1121f', '#e5383b', '#780000'],
  },
  {
    id: 'lilac',
    label: l('Сиреневый', 'Lilac'),
    hint: l('Нежно, свежо и чуть более необычно.', 'Soft, fresh, and a little less expected.'),
    emoji: '💜',
    celebration: l('Сирень добавляет характер.', 'Lilac adds a nice bit of personality.'),
    photoUrl: photo.hydrangea,
    swatch: ['#cdb4db', '#d9c2f0', '#b8a1d9'],
  },
  {
    id: 'green',
    label: l('Зеленый акцент', 'Fresh green'),
    hint: l('Свежесть, ботаничность, ощущение воздуха.', 'Fresh, botanical, airy.'),
    emoji: '🍃',
    celebration: l('Любовь к свежести засчитана.', 'Freshness has been officially noted.'),
    photoUrl: photo.pottedGreen,
    swatch: ['#adc178', '#dde5b6', '#6a994e'],
  },
]

export const shapeOptions: VisualOption<ShapeId>[] = [
  {
    id: 'airy',
    label: l('Воздух и легкость', 'Airy and loose'),
    hint: l('Как будто букет собран не по линейке.', 'Like it was arranged with taste, not a ruler.'),
    emoji: '🫧',
    celebration: l('Выбрана легкая и живая форма.', 'Light and effortless shape selected.'),
    photoUrl: photo.ranunculus,
  },
  {
    id: 'neat',
    label: l('Аккуратно и чисто', 'Neat and clean'),
    hint: l('Собранно, спокойно и без визуального шума.', 'Structured, calm, and free of visual noise.'),
    emoji: '📏',
    celebration: l('Есть любовь к чистому силуэту.', 'There is love for a clean silhouette.'),
    photoUrl: photo.tulip,
  },
  {
    id: 'mono',
    label: l('Лучше один герой', 'One hero is enough'),
    hint: l('Один тип цветка звучит понятнее, чем микс.', 'One flower type can feel much more intentional than a mix.'),
    emoji: '🌷',
    celebration: l('Моно-букеты вышли в плюс.', 'Monofloral bouquets are clearly welcome.'),
    photoUrl: photo.creamRose,
  },
  {
    id: 'lush',
    label: l('Пышно и щедро', 'Full and generous'),
    hint: l('Когда хочется объема и эффекта подарка.', 'For moments when volume and gift energy really matter.'),
    emoji: '🎁',
    celebration: l('Пышность одобрена.', 'Full bouquet energy approved.'),
    photoUrl: photo.hydrangea,
  },
]

export const gestureLevelOptions: VisualOption<GestureLevelId>[] = [
  {
    id: 'quiet',
    label: l('Мило, без пафоса', 'Sweet, not loud'),
    hint: l('Лучше трогательно, чем громко.', 'Better tender than dramatic.'),
    emoji: '🤍',
    celebration: l('Ставка на деликатность сохранена.', 'Delicate gift energy saved.'),
    photoUrl: photo.tulip,
  },
  {
    id: 'balanced',
    label: l('Заметно, но уместно', 'Noticeable, but tasteful'),
    hint: l('Хочется красиво, но без перебора.', 'Beautiful, but still appropriate.'),
    emoji: '✨',
    celebration: l('Найден очень жизненный баланс.', 'A very practical balance has been found.'),
    photoUrl: photo.peony,
  },
  {
    id: 'grand',
    label: l('Люблю когда прям вау', 'I like a real wow moment'),
    hint: l('Можно щедро, заметно и с жестом.', 'Go generous, visible, and celebratory.'),
    emoji: '💥',
    celebration: l('Разрешение на вау-эффект получено.', 'Permission for a wow moment granted.'),
    photoUrl: photo.hydrangea,
  },
]

export const scentLevelOptions: VisualOption<ScentLevelId>[] = [
  {
    id: 'low',
    label: l('Почти без запаха', 'Almost no scent'),
    hint: l('Чем деликатнее аромат, тем безопаснее.', 'The gentler the scent, the safer the gift feels.'),
    emoji: '🌫️',
    celebration: l('Запах держим на деликатном уровне.', 'Got it, the scent should stay subtle.'),
    photoUrl: photo.tulip,
  },
  {
    id: 'soft',
    label: l('Легкий аромат ок', 'A light scent is fine'),
    hint: l('Немного аромата приятно, если он не захватывает всю комнату.', 'Some scent is nice as long as it does not take over the whole room.'),
    emoji: '🤍',
    celebration: l('Легкий аромат можно оставлять в игре.', 'A soft floral scent can stay in play.'),
    photoUrl: photo.peony,
  },
  {
    id: 'strong',
    label: l('Люблю выраженный аромат', 'I enjoy a strong scent'),
    hint: l('Запах может быть частью впечатления, а не риском.', 'The scent can be part of the experience instead of a risk.'),
    emoji: '🌺',
    celebration: l('Отлично, аромат может быть частью вау-эффекта.', 'Perfect, scent can now be part of the wow factor.'),
    photoUrl: photo.lily,
  },
]

export const greeneryOptions: VisualOption<GreeneryLevelId>[] = [
  {
    id: 'minimal',
    label: l('Почти без зелени', 'Very little greenery'),
    hint: l('Фокус на самих цветах, без лишних листьев.', 'Keep the attention on the blooms, not on leafy fillers.'),
    emoji: '🌿',
    celebration: l('Ок, зелень держим на минимуме.', 'Got it, greenery should stay minimal.'),
    photoUrl: photo.creamRose,
  },
  {
    id: 'balanced',
    label: l('Немного зелени ок', 'A balanced amount'),
    hint: l('Чтобы было свежо, но не кустисто.', 'Freshness is good, but it should not look bushy.'),
    emoji: '🍃',
    celebration: l('Свежесть с мерой отмечена.', 'A balanced fresh look is now part of the profile.'),
    photoUrl: photo.peony,
  },
  {
    id: 'lush',
    label: l('Люблю ботаничный вайб', 'I like a botanical look'),
    hint: l('Больше воздуха, зелени и ощущения природности.', 'More air, more greens, more of that garden-like feel.'),
    emoji: '🌱',
    celebration: l('Ботаничная подача одобрена.', 'A more botanical presentation is welcome.'),
    photoUrl: photo.pottedGreen,
  },
]

export const wrappingStyleOptions: VisualOption<WrappingStyleId>[] = [
  {
    id: 'bare',
    label: l('Почти без упаковки', 'Almost no wrapping'),
    hint: l('Чем чище и естественнее, тем лучше.', 'The cleaner and more natural it looks, the better.'),
    emoji: '🪶',
    celebration: l('Оформление держим максимально легким.', 'Presentation should stay light and understated.'),
    photoUrl: photo.ranunculus,
  },
  {
    id: 'paper',
    label: l('Аккуратная бумага', 'Neat paper wrap'),
    hint: l('Немного оформления ок, если оно спокойное.', 'A bit of wrapping is fine when it stays soft and tasteful.'),
    emoji: '📜',
    celebration: l('Спокойная упаковка подходит.', 'A tasteful paper wrap works well here.'),
    photoUrl: photo.peony,
  },
  {
    id: 'decorative',
    label: l('Можно и наряднее', 'Decorative is fine'),
    hint: l('Лента, фактура и заметная подача не пугают.', 'Ribbons, texture, and a more dressed-up presentation are welcome.'),
    emoji: '🎀',
    celebration: l('Хорошо, можно делать подачу заметнее.', 'Nice, the presentation can be more styled.'),
    photoUrl: photo.redRose,
  },
]

export const flowerOptions: VisualOption<FlowerFamilyId>[] = [
  {
    id: 'peonies',
    label: l('Пионы', 'Peonies'),
    hint: l('Мягкие, пышные, романтичные.', 'Soft, lush, and romantic.'),
    emoji: '🌸',
    celebration: l('Пионы практически всегда выглядят как комплимент.', 'Peonies almost always feel like a compliment.'),
    photoUrl: photo.peony,
    swatch: ['#f6c8d4', '#f8d8df', '#fff5ef'],
  },
  {
    id: 'tulips',
    label: l('Тюльпаны', 'Tulips'),
    hint: l('Легкие, чистые и очень понятные.', 'Light, clean, and beautifully simple.'),
    emoji: '🌷',
    celebration: l('Тюльпаны делают все проще и свежее.', 'Tulips make everything feel easier and fresher.'),
    photoUrl: photo.tulip,
    swatch: ['#ff8fab', '#ffd166', '#f8f9fa'],
  },
  {
    id: 'ranunculus',
    label: l('Ранункулюсы', 'Ranunculus'),
    hint: l('Изящные, собранные, нежные.', 'Elegant, refined, and soft.'),
    emoji: '🪷',
    celebration: l('Очень красивый и аккуратный выбор.', 'A very refined favorite choice.'),
    photoUrl: photo.ranunculus,
    swatch: ['#f9bec7', '#eddcd2', '#dbcaf2'],
  },
  {
    id: 'roses',
    label: l('Розы', 'Roses'),
    hint: l('От супер-безопасно до слишком громко, все зависит от подачи.', 'From very safe to way too much, depending on the style.'),
    emoji: '🌹',
    celebration: l('Розы оставляем в игре, но с нюансами.', 'Roses stay in play, with nuance.'),
    photoUrl: photo.creamRose,
    swatch: ['#f28482', '#f5cac3', '#c1121f'],
  },
  {
    id: 'hydrangeas',
    label: l('Гортензии', 'Hydrangeas'),
    hint: l('Объем, мягкость и вау-фактура.', 'Volume, softness, and a real wow texture.'),
    emoji: '🫧',
    celebration: l('Есть интерес к более фактурным букетам.', 'There is interest in more textured bouquets.'),
    photoUrl: photo.hydrangea,
    swatch: ['#cdb4db', '#bde0fe', '#eff7f6'],
  },
  {
    id: 'wildflowers',
    label: l('Полевой вайб', 'Wildflower vibe'),
    hint: l('Свежо, мило, живо и не слишком формально.', 'Fresh, sweet, alive, and not too formal.'),
    emoji: '🌼',
    celebration: l('Поймано ощущение “будто собрали специально для меня”.', 'That “made especially for me” feeling has been captured.'),
    photoUrl: photo.sunnyField,
    swatch: ['#ffd166', '#adc178', '#fff8ef'],
  },
  {
    id: 'lilies',
    label: l('Лилии', 'Lilies'),
    hint: l('Выразительный аромат и очень спорные ассоциации.', 'A strong scent and very specific associations.'),
    emoji: '🤍',
    celebration: l('Отмечен важный ароматный маркер.', 'An important scent signal has been noted.'),
    photoUrl: photo.lily,
    swatch: ['#fff8ef', '#ffe8cc', '#f4d35e'],
  },
  {
    id: 'chrysanthemums',
    label: l('Хризантемы', 'Chrysanthemums'),
    hint: l('Практичные, но романтический вайб читается не всегда.', 'Practical, but not always romantic in the way you want.'),
    emoji: '🌼',
    celebration: l('Полезный стоп-сигнал для скучных букетов.', 'A very useful stop-signal for generic bouquets.'),
    photoUrl: photo.marketMix,
    swatch: ['#f7ede2', '#f6bd60', '#84a59d'],
  },
]

export const roseStyleOptions: VisualOption<RoseStyleId>[] = [
  {
    id: 'classic',
    label: l('Спокойные классические', 'Classic and calm'),
    hint: l('Светлые или нейтральные розы без драмы.', 'Lighter or neutral roses without too much drama.'),
    emoji: '🌹',
    celebration: l('Ок, если розы, то спокойные и собранные.', 'Got it, roses should stay calm and elegant.'),
    photoUrl: photo.creamRose,
  },
  {
    id: 'spray',
    label: l('Небольшие и милые', 'Smaller and sweeter'),
    hint: l('Больше ощущения “cute”, меньше официальности.', 'More cute and charming, less formal and staged.'),
    emoji: '💗',
    celebration: l('Отмечаю любовь к более милой подаче роз.', 'Nice, smaller and sweeter rose styling works better.'),
    photoUrl: photo.ranunculus,
  },
  {
    id: 'garden',
    label: l('Пышные и садовые', 'Full and garden-like'),
    hint: l('Больше объема, лепестков и вау-фактуры.', 'More volume, more petals, more of that lush garden feel.'),
    emoji: '🌺',
    celebration: l('Если розы, то можно более пышные и выразительные.', 'If roses happen, they can be fuller and more textured.'),
    photoUrl: photo.redRose,
  },
]

export const tulipStyleOptions: VisualOption<TulipStyleId>[] = [
  {
    id: 'mono',
    label: l('Аккуратный моно-букет', 'Clean mono tulips'),
    hint: l('Один цвет или очень спокойная гамма.', 'One color or a very calm palette feels best.'),
    emoji: '🌷',
    celebration: l('Тюльпаны считываются лучше, когда они очень чистые.', 'Tulips work best when they stay clean and simple.'),
    photoUrl: photo.tulip,
  },
  {
    id: 'bright',
    label: l('Ярко и по-весеннему', 'Bright and springy'),
    hint: l('Можно больше цвета и хорошего настроения.', 'More color and sunshine energy is totally fine.'),
    emoji: '☀️',
    celebration: l('Есть запрос на более солнечные тюльпаны.', 'Great, brighter tulip moods are welcome.'),
    photoUrl: photo.sunnyField,
  },
  {
    id: 'natural',
    label: l('Свободно и натурально', 'Loose and natural'),
    hint: l('Не идеально строем, а живо и чуть небрежно.', 'Not ruler-straight, but more alive and organic.'),
    emoji: '🍃',
    celebration: l('Тюльпанам можно быть менее формальными.', 'Perfect, tulips can feel a little less formal.'),
    photoUrl: photo.pottedBloom,
  },
]

export const plantStyleOptions: VisualOption<PlantStyleId>[] = [
  {
    id: 'flowering',
    label: l('Цветущие и красивые', 'Flowering and pretty'),
    hint: l('Чтобы в горшке все равно было ощущение “цветов”.', 'A potted gift should still feel floral and celebratory.'),
    emoji: '🌺',
    celebration: l('Понял, если горшок, то лучше с цветением.', 'Got it, if it is potted, it should still feel blooming and giftable.'),
    photoUrl: photo.pottedBloom,
  },
  {
    id: 'green',
    label: l('Зеленые интерьерные', 'Green interior plants'),
    hint: l('Спокойно, стильно и скорее про атмосферу дома.', 'Calm, stylish, and more about the home vibe.'),
    emoji: '🪴',
    celebration: l('Ок, зеленые растения тоже очень в тему.', 'Nice, green houseplants are definitely in play.'),
    photoUrl: photo.pottedGreen,
  },
  {
    id: 'petite',
    label: l('Небольшие и милые', 'Small and cute'),
    hint: l('Никакого громоздкого ухода и большого объема.', 'Nothing huge or high-maintenance.'),
    emoji: '🌱',
    celebration: l('Формат маленького живого подарка зафиксирован.', 'Perfect, a smaller living gift is the right scale.'),
    photoUrl: photo.petitePlant,
  },
]

export const bouquets: BouquetCardData[] = [
  {
    id: 'peony-cloud',
    title: l('Пионовое облако', 'Peony cloud'),
    subtitle: l('Мягко, объемно и очень комплиментарно', 'Soft, full, and effortlessly flattering'),
    note: l('Без официоза, но с ощущением “я старался”.', 'No stiffness, but it still says “I clearly put thought into this.”'),
    colors: ['#f6c8d4', '#f8d8df', '#fff8ef', '#f6e0cb'],
    photoUrl: photo.peony,
    emoji: '🌸',
    giftKind: 'cut',
    vibes: ['soft', 'elegant'],
    shapes: ['airy', 'lush'],
    flowerFamilies: ['peonies', 'ranunculus'],
    occasions: ['everyday', 'birthday', 'achievement'],
    intensity: 'balanced',
    scentLevel: 'soft',
    greeneryLevel: 'balanced',
    wrappingStyle: 'paper',
    universal: true,
  },
  {
    id: 'tulip-simple',
    title: l('Аккуратные тюльпаны', 'Simple tulips'),
    subtitle: l('Чисто, просто и очень уместно', 'Clean, simple, and very easy to get right'),
    note: l('Идеально, когда хочется подарить цветы без пафоса.', 'Perfect when you want flowers without overdoing the gesture.'),
    colors: ['#ff8fab', '#ffd166', '#fff8ef', '#adc178'],
    photoUrl: photo.tulip,
    emoji: '🌷',
    giftKind: 'cut',
    vibes: ['soft', 'bright'],
    shapes: ['neat', 'mono'],
    flowerFamilies: ['tulips'],
    occasions: ['everyday', 'achievement'],
    intensity: 'quiet',
    scentLevel: 'low',
    greeneryLevel: 'minimal',
    wrappingStyle: 'bare',
    tulipStyle: 'mono',
    universal: true,
  },
  {
    id: 'cream-rose',
    title: l('Кремовые розы без пафоса', 'Cream roses without the drama'),
    subtitle: l('Классика, но спокойная и взрослая', 'A classic look, but calmer and more grown-up'),
    note: l('Подходит, когда нужен элегантный жест без драмы.', 'A good option when the gesture should feel elegant, not intense.'),
    colors: ['#fff8ef', '#f5efe2', '#f8d8df'],
    photoUrl: photo.creamRose,
    emoji: '🌹',
    giftKind: 'cut',
    vibes: ['soft', 'elegant'],
    shapes: ['neat', 'mono'],
    flowerFamilies: ['roses'],
    occasions: ['everyday', 'birthday', 'apology'],
    intensity: 'balanced',
    scentLevel: 'soft',
    greeneryLevel: 'minimal',
    wrappingStyle: 'paper',
    roseStyle: 'classic',
    universal: true,
  },
  {
    id: 'ranunculus-air',
    title: l('Ранункулюсы и воздух', 'Ranunculus and air'),
    subtitle: l('Изящно, легко и очень “с заботой”', 'Refined, light, and very intentionally caring'),
    note: l('Букет для человека, который считывает детали.', 'A bouquet for someone who notices thoughtful details.'),
    colors: ['#f9bec7', '#eddcd2', '#dbcaf2', '#fff8ef'],
    photoUrl: photo.ranunculus,
    emoji: '🪷',
    giftKind: 'cut',
    vibes: ['soft', 'elegant'],
    shapes: ['airy', 'neat'],
    flowerFamilies: ['ranunculus'],
    occasions: ['everyday', 'birthday'],
    intensity: 'quiet',
    scentLevel: 'low',
    greeneryLevel: 'balanced',
    wrappingStyle: 'bare',
    universal: true,
  },
  {
    id: 'sunny-field',
    title: l('Солнечный полевой микс', 'Sunny field mix'),
    subtitle: l('Легкий, живой, как хорошее настроение', 'Light, fresh, and full of easy good mood'),
    note: l('Работает, если нравится ощущение свежести и неидеальности.', 'Works beautifully if she likes freshness and a less “perfect” arrangement.'),
    colors: ['#ffd166', '#adc178', '#ffc6a8', '#fff8ef'],
    photoUrl: photo.sunnyField,
    emoji: '🌼',
    giftKind: 'cut',
    vibes: ['bright', 'soft'],
    shapes: ['airy', 'lush'],
    flowerFamilies: ['wildflowers', 'tulips'],
    occasions: ['everyday', 'achievement'],
    intensity: 'balanced',
    scentLevel: 'soft',
    greeneryLevel: 'lush',
    wrappingStyle: 'paper',
    tulipStyle: 'bright',
    universal: false,
  },
  {
    id: 'hydrangea-glow',
    title: l('Гортензии в объеме', 'Hydrangea glow'),
    subtitle: l('Фактурно, заметно и по-праздничному', 'Textured, visible, and very celebration-coded'),
    note: l('Лучше на событие, чем на обычный день.', 'Better for a real occasion than for an ordinary date.'),
    colors: ['#cdb4db', '#bde0fe', '#eff7f6', '#adc178'],
    photoUrl: photo.hydrangea,
    emoji: '🫧',
    giftKind: 'cut',
    vibes: ['elegant', 'dramatic'],
    shapes: ['lush'],
    flowerFamilies: ['hydrangeas', 'roses'],
    occasions: ['birthday', 'achievement'],
    intensity: 'grand',
    scentLevel: 'soft',
    greeneryLevel: 'balanced',
    wrappingStyle: 'decorative',
    roseStyle: 'garden',
    universal: false,
    caution: l('Может быть слишком заметным для обычной встречи.', 'Might feel too big for an ordinary casual meetup.'),
  },
  {
    id: 'red-rose-grand',
    title: l('Красные розы в вау-режиме', 'Grand red roses'),
    subtitle: l('Сильный жест и очень конкретное настроение', 'A strong gesture with a very specific emotional tone'),
    note: l('Красиво, но не “по умолчанию” и не на каждый день.', 'Beautiful, but definitely not an automatic default choice.'),
    colors: ['#c1121f', '#9a031e', '#f4a261', '#780000'],
    photoUrl: photo.redRose,
    emoji: '❤️',
    giftKind: 'cut',
    vibes: ['dramatic', 'elegant'],
    shapes: ['mono', 'lush'],
    flowerFamilies: ['roses'],
    occasions: ['birthday', 'apology'],
    intensity: 'grand',
    scentLevel: 'soft',
    greeneryLevel: 'minimal',
    wrappingStyle: 'decorative',
    roseStyle: 'garden',
    universal: false,
    caution: l('Для обычного повода может ощущаться слишком громко.', 'For a normal day it may feel too loud and too loaded.'),
  },
  {
    id: 'lily-parade',
    title: l('Лилии с сильным ароматом', 'Strong-scent lily bouquet'),
    subtitle: l('Очень заметно и очень на любителя', 'Very noticeable and very much an acquired taste'),
    note: l('Точно не самый безопасный вариант, если вкус не обсужден.', 'Definitely not the safest option if preferences were never discussed.'),
    colors: ['#fff8ef', '#ffe8cc', '#f4d35e', '#adc178'],
    photoUrl: photo.lily,
    emoji: '🤍',
    giftKind: 'cut',
    vibes: ['elegant'],
    shapes: ['lush'],
    flowerFamilies: ['lilies'],
    occasions: ['birthday', 'apology'],
    intensity: 'grand',
    scentLevel: 'strong',
    greeneryLevel: 'balanced',
    wrappingStyle: 'paper',
    universal: false,
    caution: l('Аромат и ассоциации могут резко не зайти.', 'The scent and associations can be an immediate hard no.'),
  },
  {
    id: 'market-mix',
    title: l('Радужный маркет-микс', 'Rainbow market mix'),
    subtitle: l('Ярко, громко и немного случайно', 'Bright, loud, and a little too random'),
    note: l('Иногда выглядит как “взял первое, что было”.', 'Sometimes reads as “I just picked whatever was there.”'),
    colors: ['#ffd166', '#ef476f', '#cdb4db', '#adc178'],
    photoUrl: photo.marketMix,
    emoji: '🎉',
    giftKind: 'cut',
    vibes: ['bright'],
    shapes: ['lush'],
    flowerFamilies: ['chrysanthemums', 'roses', 'wildflowers'],
    occasions: ['birthday'],
    intensity: 'grand',
    scentLevel: 'soft',
    greeneryLevel: 'lush',
    wrappingStyle: 'decorative',
    universal: false,
    caution: l('Есть риск выглядеть небрежно и безлично.', 'High risk of feeling generic and not very thoughtful.'),
  },
  {
    id: 'blooming-orchid',
    title: l('Цветущая орхидея', 'Blooming orchid'),
    subtitle: l('Живой подарок, который выглядит аккуратно и красиво', 'A living gift that still feels elegant and giftable'),
    note: l('Хорошо, если нравятся растения в горшке и хочется чего-то более долгого.', 'Great when a potted gift feels more thoughtful than a bouquet.'),
    colors: ['#fff8ef', '#f8d8df', '#adc178', '#f5efe2'],
    photoUrl: photo.pottedBloom,
    emoji: '🪴',
    giftKind: 'potted',
    vibes: ['soft', 'elegant'],
    shapes: ['neat'],
    flowerFamilies: [],
    occasions: ['birthday', 'achievement'],
    intensity: 'balanced',
    scentLevel: 'low',
    greeneryLevel: 'balanced',
    wrappingStyle: 'paper',
    plantStyle: 'flowering',
    universal: false,
  },
  {
    id: 'green-home-plant',
    title: l('Зеленое интерьерное растение', 'Green home plant'),
    subtitle: l('Спокойно, стильно и с вайбом “останется надолго”', 'Calm, stylish, and built to stay around'),
    note: l('Скорее про атмосферу дома, чем про романтический букетный жест.', 'More about home mood and longevity than a classic romantic bouquet gesture.'),
    colors: ['#adc178', '#dde5b6', '#f5efe2', '#6a994e'],
    photoUrl: photo.pottedGreen,
    emoji: '🌿',
    giftKind: 'potted',
    vibes: ['elegant'],
    shapes: ['neat', 'lush'],
    flowerFamilies: [],
    occasions: ['everyday', 'achievement'],
    intensity: 'quiet',
    scentLevel: 'low',
    greeneryLevel: 'lush',
    wrappingStyle: 'bare',
    plantStyle: 'green',
    universal: false,
  },
  {
    id: 'petite-bloom-pot',
    title: l('Небольшое цветущее растение', 'Petite flowering plant'),
    subtitle: l('Милый живой подарок без ощущения “слишком серьезно”', 'A small living gift without the weight of a huge gesture'),
    note: l('Подходит, когда хочется чего-то живого, но компактного и простого.', 'A nice fit when a living gift should stay small, cute, and easy.'),
    colors: ['#f6c8d4', '#fff8ef', '#adc178', '#f9e6eb'],
    photoUrl: photo.petitePlant,
    emoji: '🌱',
    giftKind: 'potted',
    vibes: ['soft', 'bright'],
    shapes: ['neat'],
    flowerFamilies: [],
    occasions: ['everyday', 'birthday'],
    intensity: 'quiet',
    scentLevel: 'low',
    greeneryLevel: 'balanced',
    wrappingStyle: 'bare',
    plantStyle: 'petite',
    universal: false,
  },
]

const likesRoses = (answers: AnswerState) => answers.likedFlowers.includes('roses')
const likesTulips = (answers: AnswerState) => answers.likedFlowers.includes('tulips')
const allowsPlants = (answers: AnswerState) =>
  answers.giftFormat === 'potted' || answers.giftFormat === 'both'

export const questions: Question[] = [
  {
    id: 'giftFormat',
    field: 'giftFormat',
    type: 'single',
    eyebrow: l('Формат', 'Format'),
    title: l('Что приятнее получать?', 'What feels nicest to receive?'),
    subtitle: l('Сразу поймем: держаться букетов, растений или оставить оба варианта.', 'This tells us whether to stay in bouquet mode, plant mode, or keep both open.'),
    options: giftFormatOptions,
  },
  {
    id: 'vibe',
    field: 'vibe',
    type: 'single',
    eyebrow: l('Настроение', 'Mood'),
    title: l('Какой цветочный вайб ощущается “моим”?', 'Which floral mood feels the most like “me”?'),
    subtitle: l('Выбираем по ощущению, а не по названиям цветов.', 'Pick by feeling, not by flower terminology.'),
    options: vibeOptions,
  },
  {
    id: 'palette',
    field: 'palette',
    type: 'multi',
    eyebrow: l('Палитра', 'Palette'),
    title: l('Какие оттенки радуют глаз?', 'Which colors feel right?'),
    subtitle: l('Можно выбрать несколько. Это станет базой для рекомендаций.', 'Pick a few. This becomes the palette baseline for the report.'),
    helper: l('Лучше 2-3 фаворита, чем все сразу.', 'Two or three favorites usually work best here.'),
    options: paletteOptions,
    minSelections: 1,
    maxSelections: 3,
  },
  {
    id: 'shape',
    field: 'shape',
    type: 'single',
    eyebrow: l('Сборка', 'Shape'),
    title: l('По форме ближе что?', 'Which overall shape feels closest?'),
    subtitle: l('Не про отдельные цветы, а про силуэт целиком.', 'This is about the whole silhouette, not the flower names.'),
    options: shapeOptions,
  },
  {
    id: 'gestureLevel',
    field: 'gestureLevel',
    type: 'single',
    eyebrow: l('Масштаб', 'Gesture'),
    title: l('Насколько заметным может быть подарок?', 'How visible can the floral gesture be?'),
    subtitle: l('Чтобы потом отличить мило от “это уже слишком”.', 'This helps separate “sweet” from “that is too much”.'),
    options: gestureLevelOptions,
  },
  {
    id: 'likedFlowers',
    field: 'likedFlowers',
    type: 'multi',
    eyebrow: l('Любимчики', 'Favorites'),
    title: l('Какие цветы хочется видеть чаще?', 'Which flowers would she actually love seeing more often?'),
    subtitle: l('Выбираем визуально, без ботанического экзамена.', 'Pick visually, no flower-name exam required.'),
    helper: l('Можно отметить несколько любимчиков.', 'You can pick several favorites.'),
    options: flowerOptions,
    minSelections: 1,
    maxSelections: 4,
  },
  {
    id: 'roseStyle',
    field: 'roseStyle',
    type: 'single',
    eyebrow: l('Если про розы', 'If roses are in play'),
    title: l('Если дарить розы, то какие ближе?', 'If roses happen, which kind feels best?'),
    subtitle: l('Уточняем розы без флористических терминов.', 'This keeps rose nuance human, not florist-y.'),
    options: roseStyleOptions,
    showWhen: likesRoses,
  },
  {
    id: 'tulipStyle',
    field: 'tulipStyle',
    type: 'single',
    eyebrow: l('Если про тюльпаны', 'If tulips are in play'),
    title: l('А тюльпаны какие нравятся больше?', 'And what kind of tulips feel nicest?'),
    subtitle: l('Чтобы потом не спутать “милые” с “слишком случайными”.', 'This helps separate “cute tulips” from “too random”.'),
    options: tulipStyleOptions,
    showWhen: likesTulips,
  },
  {
    id: 'plantStyle',
    field: 'plantStyle',
    type: 'single',
    eyebrow: l('Если про горшки', 'If plants are in play'),
    title: l('Если выбирать растение, то какое?', 'If it is a plant, what kind feels right?'),
    subtitle: l('Нужна не просто “зелень”, а понятный формат подарка.', 'This turns “a plant maybe” into a practical gift preference.'),
    options: plantStyleOptions,
    showWhen: allowsPlants,
  },
  {
    id: 'scentLevel',
    field: 'scentLevel',
    type: 'single',
    eyebrow: l('Аромат', 'Scent'),
    title: l('Как с ароматом?', 'How should the scent feel?'),
    subtitle: l('Очень важный фильтр: иногда запах решает все.', 'This matters a lot because scent can make or break the whole gift.'),
    options: scentLevelOptions,
  },
  {
    id: 'greeneryLevel',
    field: 'greeneryLevel',
    type: 'single',
    eyebrow: l('Зелень', 'Greenery'),
    title: l('Сколько зелени приятно видеть?', 'How much greenery feels good?'),
    subtitle: l('Многим важнее листья и “ботаничность”, чем кажется.', 'For many people, greenery matters much more than it seems.'),
    options: greeneryOptions,
  },
  {
    id: 'wrappingStyle',
    field: 'wrappingStyle',
    type: 'single',
    eyebrow: l('Оформление', 'Wrapping'),
    title: l('Что по упаковке?', 'What about wrapping?'),
    subtitle: l('Тут легко понять, где красиво, а где уже перебор.', 'This is where tasteful can quickly turn into overdone.'),
    options: wrappingStyleOptions,
  },
  {
    id: 'bouquetReactions',
    field: 'bouquetReactions',
    type: 'bouquet',
    eyebrow: l('Mini Flinder', 'Mini Flinder'),
    title: l('Оцени примеры: что прям да, что нет?', 'React to examples: what is a yes, maybe, or no?'),
    subtitle: l('Здесь уже видны и букеты, и живые растения, если ты их допускаешь.', 'This round uses real gift examples, including plants when they are still in play.'),
    helper: l('Нужно оценить хотя бы 5 примеров.', 'Rate at least 5 examples.'),
    bouquetIds: bouquets.map((bouquet) => bouquet.id),
    minSelections: 5,
  },
  {
    id: 'avoidFlowers',
    field: 'avoidFlowers',
    type: 'multi',
    eyebrow: l('Точно нет', 'Hard no'),
    title: l('Что лучше вообще не дарить?', 'What should never be in the gift?'),
    subtitle: l('Если жестких запретов нет, этот шаг можно пропустить.', 'If there are no hard no’s, you can skip this step.'),
    helper: l('Отмеченное здесь попадет в секцию “никогда не бери”.', 'Anything selected here becomes part of the “never buy this” section.'),
    options: flowerOptions,
    minSelections: 0,
  },
]

export function getVisibleQuestions(answers: AnswerState) {
  return questions.filter((question) => !question.showWhen || question.showWhen(answers))
}

export const reactionLabels: Record<Locale, Record<BouquetReaction, string>> = {
  ru: {
    like: 'Очень да',
    maybe: 'Может быть',
    no: 'Нет',
  },
  en: {
    like: 'Love it',
    maybe: 'Maybe',
    no: 'Nope',
  },
}

export const occasionLabelMap: Record<Locale, Record<OccasionId, string>> = {
  ru: {
    everyday: 'На обычный день',
    birthday: 'На день рождения',
    apology: 'Когда нужно извиниться',
    achievement: 'На праздник или достижение',
  },
  en: {
    everyday: 'For an ordinary day',
    birthday: 'For a birthday',
    apology: 'For an apology',
    achievement: 'For a celebration',
  },
}

export const occasionReasonMap: Record<Locale, Record<OccasionId, string>> = {
  ru: {
    everyday: 'для обычного дня',
    birthday: 'для дня рождения',
    apology: 'для ситуации, где нужен теплый жест',
    achievement: 'для поздравления и красивого повода',
  },
  en: {
    everyday: 'for an everyday date',
    birthday: 'for a birthday',
    apology: 'for an apology situation',
    achievement: 'for a celebration or achievement',
  },
}

function createOptionLabelMap<T extends string>(options: VisualOption<T>[], locale: Locale) {
  return Object.fromEntries(options.map((option) => [option.id, textOf(option.label, locale)])) as Record<
    T,
    string
  >
}

export function getLocaleData(locale: Locale) {
  return {
    giftFormatLabelMap: createOptionLabelMap(giftFormatOptions, locale),
    vibeLabelMap: createOptionLabelMap(vibeOptions, locale),
    paletteLabelMap: createOptionLabelMap(paletteOptions, locale),
    shapeLabelMap: createOptionLabelMap(shapeOptions, locale),
    gestureLabelMap: createOptionLabelMap(gestureLevelOptions, locale),
    scentLabelMap: createOptionLabelMap(scentLevelOptions, locale),
    greeneryLabelMap: createOptionLabelMap(greeneryOptions, locale),
    wrappingLabelMap: createOptionLabelMap(wrappingStyleOptions, locale),
    flowerLabelMap: createOptionLabelMap(flowerOptions, locale),
    roseStyleLabelMap: createOptionLabelMap(roseStyleOptions, locale),
    tulipStyleLabelMap: createOptionLabelMap(tulipStyleOptions, locale),
    plantStyleLabelMap: createOptionLabelMap(plantStyleOptions, locale),
    reactionLabels: reactionLabels[locale],
    occasionLabelMap: occasionLabelMap[locale],
    occasionReasonMap: occasionReasonMap[locale],
  }
}

export const optionSwatches = {
  palette: Object.fromEntries(
    paletteOptions.map((option) => [option.id, option.swatch ?? []]),
  ) as Record<PaletteId, string[]>,
  flowers: Object.fromEntries(
    flowerOptions.map((option) => [option.id, option.swatch ?? []]),
  ) as Record<FlowerFamilyId, string[]>,
}

export const validIds = {
  giftFormats: new Set(giftFormatOptions.map((option) => option.id)),
  vibes: new Set(vibeOptions.map((option) => option.id)),
  palette: new Set(paletteOptions.map((option) => option.id)),
  shapes: new Set(shapeOptions.map((option) => option.id)),
  gestures: new Set(gestureLevelOptions.map((option) => option.id)),
  scents: new Set(scentLevelOptions.map((option) => option.id)),
  greenery: new Set(greeneryOptions.map((option) => option.id)),
  wrapping: new Set(wrappingStyleOptions.map((option) => option.id)),
  flowers: new Set(flowerOptions.map((option) => option.id)),
  roseStyles: new Set(roseStyleOptions.map((option) => option.id)),
  tulipStyles: new Set(tulipStyleOptions.map((option) => option.id)),
  plantStyles: new Set(plantStyleOptions.map((option) => option.id)),
  bouquets: new Set(bouquets.map((bouquet) => bouquet.id)),
}
